export interface WorldCity {
  id: string;
  city: string;
  country: string;
  timezone: string;
  flag: string;
  alwaysOn?: boolean;
}

export const WORLD_CITIES: WorldCity[] = [
  // ── Home ──────────────────────────────────────────────────────────────────
  { id: 'pk',  city: 'Multan',          country: 'Pakistan',          timezone: 'Asia/Karachi',              flag: 'PK', alwaysOn: true },

  // ── Americas ──────────────────────────────────────────────────────────────
  { id: 'nyc', city: 'New York',        country: 'USA',               timezone: 'America/New_York',          flag: 'US' },
  { id: 'lax', city: 'Los Angeles',     country: 'USA',               timezone: 'America/Los_Angeles',       flag: 'US' },
  { id: 'chi', city: 'Chicago',         country: 'USA',               timezone: 'America/Chicago',           flag: 'US' },
  { id: 'mia', city: 'Miami',           country: 'USA',               timezone: 'America/New_York',          flag: 'US' },
  { id: 'hou', city: 'Houston',         country: 'USA',               timezone: 'America/Chicago',           flag: 'US' },
  { id: 'dal', city: 'Dallas',          country: 'USA',               timezone: 'America/Chicago',           flag: 'US' },
  { id: 'den', city: 'Denver',          country: 'USA',               timezone: 'America/Denver',            flag: 'US' },
  { id: 'phx', city: 'Phoenix',         country: 'USA',               timezone: 'America/Phoenix',           flag: 'US' },
  { id: 'sea', city: 'Seattle',         country: 'USA',               timezone: 'America/Los_Angeles',       flag: 'US' },
  { id: 'sfo', city: 'San Francisco',   country: 'USA',               timezone: 'America/Los_Angeles',       flag: 'US' },
  { id: 'bos', city: 'Boston',          country: 'USA',               timezone: 'America/New_York',          flag: 'US' },
  { id: 'atl', city: 'Atlanta',         country: 'USA',               timezone: 'America/New_York',          flag: 'US' },
  { id: 'hnl', city: 'Honolulu',        country: 'USA',               timezone: 'Pacific/Honolulu',          flag: 'US' },
  { id: 'anc', city: 'Anchorage',       country: 'USA',               timezone: 'America/Anchorage',         flag: 'US' },
  { id: 'tor', city: 'Toronto',         country: 'Canada',            timezone: 'America/Toronto',           flag: 'CA' },
  { id: 'van', city: 'Vancouver',       country: 'Canada',            timezone: 'America/Vancouver',         flag: 'CA' },
  { id: 'mtl', city: 'Montreal',        country: 'Canada',            timezone: 'America/Montreal',          flag: 'CA' },
  { id: 'cal', city: 'Calgary',         country: 'Canada',            timezone: 'America/Edmonton',          flag: 'CA' },
  { id: 'mex', city: 'Mexico City',     country: 'Mexico',            timezone: 'America/Mexico_City',       flag: 'MX' },
  { id: 'gua', city: 'Guatemala City',  country: 'Guatemala',         timezone: 'America/Guatemala',         flag: 'GT' },
  { id: 'bog', city: 'Bogotá',          country: 'Colombia',          timezone: 'America/Bogota',            flag: 'CO' },
  { id: 'lim', city: 'Lima',            country: 'Peru',              timezone: 'America/Lima',              flag: 'PE' },
  { id: 'scl', city: 'Santiago',        country: 'Chile',             timezone: 'America/Santiago',          flag: 'CL' },
  { id: 'bue', city: 'Buenos Aires',    country: 'Argentina',         timezone: 'America/Argentina/Buenos_Aires', flag: 'AR' },
  { id: 'sao', city: 'São Paulo',       country: 'Brazil',            timezone: 'America/Sao_Paulo',         flag: 'BR' },
  { id: 'rio', city: 'Rio de Janeiro',  country: 'Brazil',            timezone: 'America/Sao_Paulo',         flag: 'BR' },
  { id: 'crc', city: 'Caracas',         country: 'Venezuela',         timezone: 'America/Caracas',           flag: 'VE' },
  { id: 'mvu', city: 'Montevideo',      country: 'Uruguay',           timezone: 'America/Montevideo',        flag: 'UY' },
  { id: 'pan', city: 'Panama City',     country: 'Panama',            timezone: 'America/Panama',            flag: 'PA' },
  { id: 'hav', city: 'Havana',          country: 'Cuba',              timezone: 'America/Havana',            flag: 'CU' },

  // ── Europe ────────────────────────────────────────────────────────────────
  { id: 'lon', city: 'London',          country: 'UK',                timezone: 'Europe/London',             flag: 'GB' },
  { id: 'par', city: 'Paris',           country: 'France',            timezone: 'Europe/Paris',              flag: 'FR' },
  { id: 'ber', city: 'Berlin',          country: 'Germany',           timezone: 'Europe/Berlin',             flag: 'DE' },
  { id: 'muc', city: 'Munich',          country: 'Germany',           timezone: 'Europe/Berlin',             flag: 'DE' },
  { id: 'mad', city: 'Madrid',          country: 'Spain',             timezone: 'Europe/Madrid',             flag: 'ES' },
  { id: 'bcn', city: 'Barcelona',       country: 'Spain',             timezone: 'Europe/Madrid',             flag: 'ES' },
  { id: 'rom', city: 'Rome',            country: 'Italy',             timezone: 'Europe/Rome',               flag: 'IT' },
  { id: 'mil', city: 'Milan',           country: 'Italy',             timezone: 'Europe/Rome',               flag: 'IT' },
  { id: 'ams', city: 'Amsterdam',       country: 'Netherlands',       timezone: 'Europe/Amsterdam',          flag: 'NL' },
  { id: 'bru', city: 'Brussels',        country: 'Belgium',           timezone: 'Europe/Brussels',           flag: 'BE' },
  { id: 'zur', city: 'Zurich',          country: 'Switzerland',       timezone: 'Europe/Zurich',             flag: 'CH' },
  { id: 'vie', city: 'Vienna',          country: 'Austria',           timezone: 'Europe/Vienna',             flag: 'AT' },
  { id: 'pra', city: 'Prague',          country: 'Czech Republic',    timezone: 'Europe/Prague',             flag: 'CZ' },
  { id: 'war', city: 'Warsaw',          country: 'Poland',            timezone: 'Europe/Warsaw',             flag: 'PL' },
  { id: 'bud', city: 'Budapest',        country: 'Hungary',           timezone: 'Europe/Budapest',           flag: 'HU' },
  { id: 'buc', city: 'Bucharest',       country: 'Romania',           timezone: 'Europe/Bucharest',          flag: 'RO' },
  { id: 'ath', city: 'Athens',          country: 'Greece',            timezone: 'Europe/Athens',             flag: 'GR' },
  { id: 'lis', city: 'Lisbon',          country: 'Portugal',          timezone: 'Europe/Lisbon',             flag: 'PT' },
  { id: 'dub', city: 'Dublin',          country: 'Ireland',           timezone: 'Europe/Dublin',             flag: 'IE' },
  { id: 'sto', city: 'Stockholm',       country: 'Sweden',            timezone: 'Europe/Stockholm',          flag: 'SE' },
  { id: 'osl', city: 'Oslo',            country: 'Norway',            timezone: 'Europe/Oslo',               flag: 'NO' },
  { id: 'cph', city: 'Copenhagen',      country: 'Denmark',           timezone: 'Europe/Copenhagen',         flag: 'DK' },
  { id: 'hel', city: 'Helsinki',        country: 'Finland',           timezone: 'Europe/Helsinki',           flag: 'FI' },
  { id: 'mos', city: 'Moscow',          country: 'Russia',            timezone: 'Europe/Moscow',             flag: 'RU' },
  { id: 'spb', city: 'St. Petersburg',  country: 'Russia',            timezone: 'Europe/Moscow',             flag: 'RU' },
  { id: 'kev', city: 'Kyiv',            country: 'Ukraine',           timezone: 'Europe/Kyiv',               flag: 'UA' },
  { id: 'sof', city: 'Sofia',           country: 'Bulgaria',          timezone: 'Europe/Sofia',              flag: 'BG' },
  { id: 'bel', city: 'Belgrade',        country: 'Serbia',            timezone: 'Europe/Belgrade',           flag: 'RS' },
  { id: 'zag', city: 'Zagreb',          country: 'Croatia',           timezone: 'Europe/Zagreb',             flag: 'HR' },
  { id: 'rey', city: 'Reykjavik',       country: 'Iceland',           timezone: 'Atlantic/Reykjavik',        flag: 'IS' },
  { id: 'hel2', city: 'Tallinn',        country: 'Estonia',           timezone: 'Europe/Tallinn',            flag: 'EE' },
  { id: 'rig', city: 'Riga',            country: 'Latvia',            timezone: 'Europe/Riga',               flag: 'LV' },
  { id: 'vil', city: 'Vilnius',         country: 'Lithuania',         timezone: 'Europe/Vilnius',            flag: 'LT' },

  // ── Middle East ───────────────────────────────────────────────────────────
  { id: 'ist', city: 'Istanbul',        country: 'Turkey',            timezone: 'Europe/Istanbul',           flag: 'TR' },
  { id: 'dxb', city: 'Dubai',           country: 'UAE',               timezone: 'Asia/Dubai',                flag: 'AE' },
  { id: 'aby', city: 'Abu Dhabi',       country: 'UAE',               timezone: 'Asia/Dubai',                flag: 'AE' },
  { id: 'riy', city: 'Riyadh',          country: 'Saudi Arabia',      timezone: 'Asia/Riyadh',               flag: 'SA' },
  { id: 'jed', city: 'Jeddah',          country: 'Saudi Arabia',      timezone: 'Asia/Riyadh',               flag: 'SA' },
  { id: 'kuw', city: 'Kuwait City',     country: 'Kuwait',            timezone: 'Asia/Kuwait',               flag: 'KW' },
  { id: 'doh', city: 'Doha',            country: 'Qatar',             timezone: 'Asia/Qatar',                flag: 'QA' },
  { id: 'man', city: 'Muscat',          country: 'Oman',              timezone: 'Asia/Muscat',               flag: 'OM' },
  { id: 'bah', city: 'Manama',          country: 'Bahrain',           timezone: 'Asia/Bahrain',              flag: 'BH' },
  { id: 'teh', city: 'Tehran',          country: 'Iran',              timezone: 'Asia/Tehran',               flag: 'IR' },
  { id: 'bag', city: 'Baghdad',         country: 'Iraq',              timezone: 'Asia/Baghdad',              flag: 'IQ' },
  { id: 'bei', city: 'Beirut',          country: 'Lebanon',           timezone: 'Asia/Beirut',               flag: 'LB' },
  { id: 'amm', city: 'Amman',           country: 'Jordan',            timezone: 'Asia/Amman',                flag: 'JO' },
  { id: 'jrs', city: 'Jerusalem',       country: 'Israel',            timezone: 'Asia/Jerusalem',            flag: 'IL' },
  { id: 'tlv', city: 'Tel Aviv',        country: 'Israel',            timezone: 'Asia/Jerusalem',            flag: 'IL' },
  { id: 'ana', city: 'Ankara',          country: 'Turkey',            timezone: 'Europe/Istanbul',           flag: 'TR' },

  // ── Central Asia ──────────────────────────────────────────────────────────
  { id: 'tas', city: 'Tashkent',        country: 'Uzbekistan',        timezone: 'Asia/Tashkent',             flag: 'UZ' },
  { id: 'alm', city: 'Almaty',          country: 'Kazakhstan',        timezone: 'Asia/Almaty',               flag: 'KZ' },
  { id: 'nur', city: 'Astana',          country: 'Kazakhstan',        timezone: 'Asia/Almaty',               flag: 'KZ' },
  { id: 'bak', city: 'Baku',            country: 'Azerbaijan',        timezone: 'Asia/Baku',                 flag: 'AZ' },
  { id: 'tbi', city: 'Tbilisi',         country: 'Georgia',           timezone: 'Asia/Tbilisi',              flag: 'GE' },
  { id: 'yer', city: 'Yerevan',         country: 'Armenia',           timezone: 'Asia/Yerevan',              flag: 'AM' },
  { id: 'kab', city: 'Kabul',           country: 'Afghanistan',       timezone: 'Asia/Kabul',                flag: 'AF' },

  // ── South Asia ────────────────────────────────────────────────────────────
  { id: 'isb', city: 'Islamabad',       country: 'Pakistan',          timezone: 'Asia/Karachi',              flag: 'PK' },
  { id: 'khi', city: 'Karachi',         country: 'Pakistan',          timezone: 'Asia/Karachi',              flag: 'PK' },
  { id: 'lhe', city: 'Lahore',          country: 'Pakistan',          timezone: 'Asia/Karachi',              flag: 'PK' },
  { id: 'del', city: 'New Delhi',       country: 'India',             timezone: 'Asia/Kolkata',              flag: 'IN' },
  { id: 'bom', city: 'Mumbai',          country: 'India',             timezone: 'Asia/Kolkata',              flag: 'IN' },
  { id: 'blr', city: 'Bangalore',       country: 'India',             timezone: 'Asia/Kolkata',              flag: 'IN' },
  { id: 'maa', city: 'Chennai',         country: 'India',             timezone: 'Asia/Kolkata',              flag: 'IN' },
  { id: 'ccu', city: 'Kolkata',         country: 'India',             timezone: 'Asia/Kolkata',              flag: 'IN' },
  { id: 'hyd', city: 'Hyderabad',       country: 'India',             timezone: 'Asia/Kolkata',              flag: 'IN' },
  { id: 'dac', city: 'Dhaka',           country: 'Bangladesh',        timezone: 'Asia/Dhaka',                flag: 'BD' },
  { id: 'ktm', city: 'Kathmandu',       country: 'Nepal',             timezone: 'Asia/Kathmandu',            flag: 'NP' },
  { id: 'cmb', city: 'Colombo',         country: 'Sri Lanka',         timezone: 'Asia/Colombo',              flag: 'LK' },
  { id: 'mle', city: 'Malé',            country: 'Maldives',          timezone: 'Indian/Maldives',           flag: 'MV' },

  // ── Southeast Asia ────────────────────────────────────────────────────────
  { id: 'rgn', city: 'Yangon',          country: 'Myanmar',           timezone: 'Asia/Rangoon',              flag: 'MM' },
  { id: 'bkk', city: 'Bangkok',         country: 'Thailand',          timezone: 'Asia/Bangkok',              flag: 'TH' },
  { id: 'pnh', city: 'Phnom Penh',      country: 'Cambodia',          timezone: 'Asia/Phnom_Penh',           flag: 'KH' },
  { id: 'vte', city: 'Vientiane',       country: 'Laos',              timezone: 'Asia/Vientiane',            flag: 'LA' },
  { id: 'sgn', city: 'Ho Chi Minh',     country: 'Vietnam',           timezone: 'Asia/Ho_Chi_Minh',          flag: 'VN' },
  { id: 'han', city: 'Hanoi',           country: 'Vietnam',           timezone: 'Asia/Bangkok',              flag: 'VN' },
  { id: 'kul', city: 'Kuala Lumpur',    country: 'Malaysia',          timezone: 'Asia/Kuala_Lumpur',         flag: 'MY' },
  { id: 'sin', city: 'Singapore',       country: 'Singapore',         timezone: 'Asia/Singapore',            flag: 'SG' },
  { id: 'jkt', city: 'Jakarta',         country: 'Indonesia',         timezone: 'Asia/Jakarta',              flag: 'ID' },
  { id: 'mnl', city: 'Manila',          country: 'Philippines',       timezone: 'Asia/Manila',               flag: 'PH' },
  { id: 'cgk', city: 'Bali',            country: 'Indonesia',         timezone: 'Asia/Makassar',             flag: 'ID' },
  { id: 'bnb', city: 'Bandar Seri Begawan', country: 'Brunei',        timezone: 'Asia/Brunei',               flag: 'BN' },

  // ── East Asia ────────────────────────────────────────────────────────────
  { id: 'pek', city: 'Beijing',         country: 'China',             timezone: 'Asia/Shanghai',             flag: 'CN' },
  { id: 'sha', city: 'Shanghai',        country: 'China',             timezone: 'Asia/Shanghai',             flag: 'CN' },
  { id: 'szu', city: 'Shenzhen',        country: 'China',             timezone: 'Asia/Shanghai',             flag: 'CN' },
  { id: 'gza', city: 'Guangzhou',       country: 'China',             timezone: 'Asia/Shanghai',             flag: 'CN' },
  { id: 'ctg', city: 'Chengdu',         country: 'China',             timezone: 'Asia/Shanghai',             flag: 'CN' },
  { id: 'hkg', city: 'Hong Kong',       country: 'Hong Kong',         timezone: 'Asia/Hong_Kong',            flag: 'HK' },
  { id: 'mac', city: 'Macau',           country: 'Macau',             timezone: 'Asia/Macau',                flag: 'MO' },
  { id: 'tpe', city: 'Taipei',          country: 'Taiwan',            timezone: 'Asia/Taipei',               flag: 'TW' },
  { id: 'sel', city: 'Seoul',           country: 'South Korea',       timezone: 'Asia/Seoul',                flag: 'KR' },
  { id: 'pus', city: 'Busan',           country: 'South Korea',       timezone: 'Asia/Seoul',                flag: 'KR' },
  { id: 'tyo', city: 'Tokyo',           country: 'Japan',             timezone: 'Asia/Tokyo',                flag: 'JP' },
  { id: 'osk', city: 'Osaka',           country: 'Japan',             timezone: 'Asia/Tokyo',                flag: 'JP' },
  { id: 'sap', city: 'Sapporo',         country: 'Japan',             timezone: 'Asia/Tokyo',                flag: 'JP' },
  { id: 'uln', city: 'Ulaanbaatar',     country: 'Mongolia',          timezone: 'Asia/Ulaanbaatar',          flag: 'MN' },

  // ── Africa ────────────────────────────────────────────────────────────────
  { id: 'cai', city: 'Cairo',           country: 'Egypt',             timezone: 'Africa/Cairo',              flag: 'EG' },
  { id: 'cas', city: 'Casablanca',      country: 'Morocco',           timezone: 'Africa/Casablanca',         flag: 'MA' },
  { id: 'tun', city: 'Tunis',           country: 'Tunisia',           timezone: 'Africa/Tunis',              flag: 'TN' },
  { id: 'alg', city: 'Algiers',         country: 'Algeria',           timezone: 'Africa/Algiers',            flag: 'DZ' },
  { id: 'tri', city: 'Tripoli',         country: 'Libya',             timezone: 'Africa/Tripoli',            flag: 'LY' },
  { id: 'khr', city: 'Khartoum',        country: 'Sudan',             timezone: 'Africa/Khartoum',           flag: 'SD' },
  { id: 'lag', city: 'Lagos',           country: 'Nigeria',           timezone: 'Africa/Lagos',              flag: 'NG' },
  { id: 'abj', city: 'Abidjan',         country: 'Côte d\'Ivoire',   timezone: 'Africa/Abidjan',            flag: 'CI' },
  { id: 'dak', city: 'Dakar',           country: 'Senegal',           timezone: 'Africa/Dakar',              flag: 'SN' },
  { id: 'acc', city: 'Accra',           country: 'Ghana',             timezone: 'Africa/Accra',              flag: 'GH' },
  { id: 'nbo', city: 'Nairobi',         country: 'Kenya',             timezone: 'Africa/Nairobi',            flag: 'KE' },
  { id: 'add', city: 'Addis Ababa',     country: 'Ethiopia',          timezone: 'Africa/Addis_Ababa',        flag: 'ET' },
  { id: 'dar', city: 'Dar es Salaam',   country: 'Tanzania',          timezone: 'Africa/Dar_es_Salaam',      flag: 'TZ' },
  { id: 'kmp', city: 'Kampala',         country: 'Uganda',            timezone: 'Africa/Kampala',            flag: 'UG' },
  { id: 'lun', city: 'Lusaka',          country: 'Zambia',            timezone: 'Africa/Lusaka',             flag: 'ZM' },
  { id: 'hre', city: 'Harare',          country: 'Zimbabwe',          timezone: 'Africa/Harare',             flag: 'ZW' },
  { id: 'jnb', city: 'Johannesburg',    country: 'South Africa',      timezone: 'Africa/Johannesburg',       flag: 'ZA' },
  { id: 'cpt', city: 'Cape Town',       country: 'South Africa',      timezone: 'Africa/Johannesburg',       flag: 'ZA' },
  { id: 'dkr', city: 'Dakar',           country: 'Senegal',           timezone: 'Africa/Dakar',              flag: 'SN' },
  { id: 'luanda', city: 'Luanda',       country: 'Angola',            timezone: 'Africa/Luanda',             flag: 'AO' },
  { id: 'maputo', city: 'Maputo',       country: 'Mozambique',        timezone: 'Africa/Maputo',             flag: 'MZ' },

  // ── Pacific ───────────────────────────────────────────────────────────────
  { id: 'syd', city: 'Sydney',          country: 'Australia',         timezone: 'Australia/Sydney',          flag: 'AU' },
  { id: 'mel', city: 'Melbourne',       country: 'Australia',         timezone: 'Australia/Melbourne',       flag: 'AU' },
  { id: 'bne', city: 'Brisbane',        country: 'Australia',         timezone: 'Australia/Brisbane',        flag: 'AU' },
  { id: 'per', city: 'Perth',           country: 'Australia',         timezone: 'Australia/Perth',           flag: 'AU' },
  { id: 'adl', city: 'Adelaide',        country: 'Australia',         timezone: 'Australia/Adelaide',        flag: 'AU' },
  { id: 'drw', city: 'Darwin',          country: 'Australia',         timezone: 'Australia/Darwin',          flag: 'AU' },
  { id: 'akl', city: 'Auckland',        country: 'New Zealand',       timezone: 'Pacific/Auckland',          flag: 'NZ' },
  { id: 'wlg', city: 'Wellington',      country: 'New Zealand',       timezone: 'Pacific/Auckland',          flag: 'NZ' },
  { id: 'suv', city: 'Suva',            country: 'Fiji',              timezone: 'Pacific/Fiji',              flag: 'FJ' },
  { id: 'ppt', city: 'Papeete',         country: 'French Polynesia',  timezone: 'Pacific/Tahiti',            flag: 'PF' },
  { id: 'por', city: 'Port Moresby',    country: 'Papua New Guinea',  timezone: 'Pacific/Port_Moresby',      flag: 'PG' },
  { id: 'nms', city: 'Nouméa',          country: 'New Caledonia',     timezone: 'Pacific/Noumea',            flag: 'NC' },
  { id: 'apia', city: 'Apia',           country: 'Samoa',             timezone: 'Pacific/Apia',              flag: 'WS' },
  { id: 'nuk', city: 'Nukuʻalofa',      country: 'Tonga',             timezone: 'Pacific/Tongatapu',         flag: 'TO' },
];
